# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Graphite
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  isDefault: false
  url: http://prometheus:9090
  # don't use this in prod
  editable: true

- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
  apiVersion: 1
  uid: tempo-query

# - name: Jaeger (Tempo)
#   type: jaeger
#   access: proxy
#   orgId: 1
#   url: http://tempo-query:16686
#   basicAuth: false
#   isDefault: false
#   version: 1
#   editable: false
#   apiVersion: 1
#   uid: jaeger-tempo

- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  editable: false
  jsonData:
      maxLines: 5000

- name: Postgres
  type: postgres
  access: proxy
  url: postgres:5432
  # don't use this in prod
  editable: true
  database: toggl_development
  user: xn3cr0nx
  # secureJsonData:
  #   password: password
  jsonData:
    sslmode: "disable"