extensions:
  memory_ballast:
    size_mib: 512
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 4G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

exporters:
  logging:
    loglevel: debug
  # Data sources: traces
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

  # # Data sources: metrics
  prometheus:
    # endpoint: prometheus:8889
    endpoint: prometheus:9090
    namespace: default

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]

  extensions: [memory_ballast, zpages]